Для команды /dbupdate добавлен параметр -dynamic
oscript-library/deployka pull request #29
Opened 2018-01-24 10:24 UTC by SmokyAce

Для использования возможности динамического обновления конфигурации БД.
Понятно что такой сценарий желательно не использовать, но все же бывают случаи когда это необходимо.

2018-01-24 10:42 UTC, artbear requested changes
Есть опечатка

2018-01-24 10:42 UTC, artbear commented on README.md
> +* -dinamic - Динамическое обновление конфигурации
Правильнее все-таки `-dynamic`, а не `-dinamic`

2018-01-24 10:42 UTC, artbear commented on README.md
> +* -dinamic - Динамическое обновление конфигурации
Тем более, что ниже в коде явно указано `-dynamic`

2018-01-24 10:45 UTC, SmokyAce commented on README.md
> +* -dinamic - Динамическое обновление конфигурации
Да действительно, поправлю ((

2018-01-24 10:52 UTC, artbear approved these changes
Теперь все верно.

2018-01-24 10:53 UTC, artbear commented
@EvilBeaver добавляем динамическое обновление?
Лично я его очень не люблю и не юзаю. 
А ты что скажешь ?

2018-01-24 18:59 UTC, EvilBeaver commented
@artbear ну это не повод его запрещать. Раз понадобилось кому-то значит смысл есть.

2018-01-24 19:00 UTC, EvilBeaver commented
@SmokyAce а тесты прошли?

2018-01-24 19:40 UTC, SmokyAce commented
Тесты видел, но если честно не прогонял, не вижу чем запустить. Ткните пальцем :)

2018-01-25 05:28 UTC, nixel2007 commented
Необходимо поставить пакет 1testrunner через opm и выполнить 1testrunner -runall tests

2018-01-25 08:03 UTC, SmokyAce commented
@nixel2007 Спасибо.

@EvilBeaver А тесты то не прошли ...

Тест №5: Тест_ДолженПрочитатьСписокОбъектов

ОШИБКА: Тест: <Тест_ДолженПрочитатьСписокОбъектов>
Файл: <D:\Program Files\OneScript\lib\deployka\tests\ТестПарсераВыводаRAC.os>
Сообщение: {Модуль D:\Program Files\OneScript\lib\deployka\tests\ТестПарсераВыводаRAC.os / Ошибка в строке: 31 / Метод объекта не обнаружен (РазобратьПоток)}
    Результат = КомандаУправления.РазобратьПоток(Поток);

И действительно такого метода в классе нет, он есть СерверАдминистрирования.os

2018-01-25 08:25 UTC, merged

2018-01-25 08:25 UTC, nixel2007 commented
Спасибо!

по тестам заведу ишуз

2018-01-25 08:29 UTC, Toria90 commented
Это я поломала. Забыла про тесты:(